services:
  friends-nearby-postgis:
    image: postgis/postgis
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DS_FRIENDS_NEARBY_USERNAME}
      POSTGRES_PASSWORD: ${DS_FRIENDS_NEARBY_PASSWORD}
      POSTGRES_DB: ${DS_FRIENDS_NEARBY_DB}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
    ports:
      - "7474:7474"
      - "7687:7687"


